# This file has been generated by node2nix 1.1.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "express-4.14.0" = {
      name = "express";
      packageName = "express";
      version = "4.14.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/express/-/express-4.14.0.tgz";
        sha1 = "c1ee3f42cdc891fb3dc650a8922d51ec847d0d66";
      };
    };
    "accepts-1.3.3" = {
      name = "accepts";
      packageName = "accepts";
      version = "1.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/accepts/-/accepts-1.3.3.tgz";
        sha1 = "c3ca7434938648c3e0d9c1e328dd68b622c284ca";
      };
    };
    "array-flatten-1.1.1" = {
      name = "array-flatten";
      packageName = "array-flatten";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/array-flatten/-/array-flatten-1.1.1.tgz";
        sha1 = "9a5f699051b1e7073328f2a008968b64ea2955d2";
      };
    };
    "content-disposition-0.5.1" = {
      name = "content-disposition";
      packageName = "content-disposition";
      version = "0.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/content-disposition/-/content-disposition-0.5.1.tgz";
        sha1 = "87476c6a67c8daa87e32e87616df883ba7fb071b";
      };
    };
    "content-type-1.0.2" = {
      name = "content-type";
      packageName = "content-type";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/content-type/-/content-type-1.0.2.tgz";
        sha1 = "b7d113aee7a8dd27bd21133c4dc2529df1721eed";
      };
    };
    "cookie-0.3.1" = {
      name = "cookie";
      packageName = "cookie";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/cookie/-/cookie-0.3.1.tgz";
        sha1 = "e7e0a1f9ef43b4c8ba925c5c5a96e806d16873bb";
      };
    };
    "cookie-signature-1.0.6" = {
      name = "cookie-signature";
      packageName = "cookie-signature";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/cookie-signature/-/cookie-signature-1.0.6.tgz";
        sha1 = "e303a882b342cc3ee8ca513a79999734dab3ae2c";
      };
    };
    "debug-2.2.0" = {
      name = "debug";
      packageName = "debug";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-2.2.0.tgz";
        sha1 = "f87057e995b1a1f6ae6a4960664137bc56f039da";
      };
    };
    "depd-1.1.0" = {
      name = "depd";
      packageName = "depd";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/depd/-/depd-1.1.0.tgz";
        sha1 = "e1bd82c6aab6ced965b97b88b17ed3e528ca18c3";
      };
    };
    "encodeurl-1.0.1" = {
      name = "encodeurl";
      packageName = "encodeurl";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/encodeurl/-/encodeurl-1.0.1.tgz";
        sha1 = "79e3d58655346909fe6f0f45a5de68103b294d20";
      };
    };
    "escape-html-1.0.3" = {
      name = "escape-html";
      packageName = "escape-html";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-html/-/escape-html-1.0.3.tgz";
        sha1 = "0258eae4d3d0c0974de1c169188ef0051d1d1988";
      };
    };
    "etag-1.7.0" = {
      name = "etag";
      packageName = "etag";
      version = "1.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/etag/-/etag-1.7.0.tgz";
        sha1 = "03d30b5f67dd6e632d2945d30d6652731a34d5d8";
      };
    };
    "finalhandler-0.5.0" = {
      name = "finalhandler";
      packageName = "finalhandler";
      version = "0.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/finalhandler/-/finalhandler-0.5.0.tgz";
        sha1 = "e9508abece9b6dba871a6942a1d7911b91911ac7";
      };
    };
    "fresh-0.3.0" = {
      name = "fresh";
      packageName = "fresh";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fresh/-/fresh-0.3.0.tgz";
        sha1 = "651f838e22424e7566de161d8358caa199f83d4f";
      };
    };
    "merge-descriptors-1.0.1" = {
      name = "merge-descriptors";
      packageName = "merge-descriptors";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/merge-descriptors/-/merge-descriptors-1.0.1.tgz";
        sha1 = "b00aaa556dd8b44568150ec9d1b953f3f90cbb61";
      };
    };
    "methods-1.1.2" = {
      name = "methods";
      packageName = "methods";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/methods/-/methods-1.1.2.tgz";
        sha1 = "5529a4d67654134edcc5266656835b0f851afcee";
      };
    };
    "on-finished-2.3.0" = {
      name = "on-finished";
      packageName = "on-finished";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/on-finished/-/on-finished-2.3.0.tgz";
        sha1 = "20f1336481b083cd75337992a16971aa2d906947";
      };
    };
    "parseurl-1.3.1" = {
      name = "parseurl";
      packageName = "parseurl";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/parseurl/-/parseurl-1.3.1.tgz";
        sha1 = "c8ab8c9223ba34888aa64a297b28853bec18da56";
      };
    };
    "path-to-regexp-0.1.7" = {
      name = "path-to-regexp";
      packageName = "path-to-regexp";
      version = "0.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-to-regexp/-/path-to-regexp-0.1.7.tgz";
        sha1 = "df604178005f522f15eb4490e7247a1bfaa67f8c";
      };
    };
    "proxy-addr-1.1.2" = {
      name = "proxy-addr";
      packageName = "proxy-addr";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/proxy-addr/-/proxy-addr-1.1.2.tgz";
        sha1 = "b4cc5f22610d9535824c123aef9d3cf73c40ba37";
      };
    };
    "qs-6.2.0" = {
      name = "qs";
      packageName = "qs";
      version = "6.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/qs/-/qs-6.2.0.tgz";
        sha1 = "3b7848c03c2dece69a9522b0fae8c4126d745f3b";
      };
    };
    "range-parser-1.2.0" = {
      name = "range-parser";
      packageName = "range-parser";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/range-parser/-/range-parser-1.2.0.tgz";
        sha1 = "f49be6b487894ddc40dcc94a322f611092e00d5e";
      };
    };
    "send-0.14.1" = {
      name = "send";
      packageName = "send";
      version = "0.14.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/send/-/send-0.14.1.tgz";
        sha1 = "a954984325392f51532a7760760e459598c89f7a";
      };
    };
    "serve-static-1.11.1" = {
      name = "serve-static";
      packageName = "serve-static";
      version = "1.11.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/serve-static/-/serve-static-1.11.1.tgz";
        sha1 = "d6cce7693505f733c759de57befc1af76c0f0805";
      };
    };
    "type-is-1.6.14" = {
      name = "type-is";
      packageName = "type-is";
      version = "1.6.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/type-is/-/type-is-1.6.14.tgz";
        sha1 = "e219639c17ded1ca0789092dd54a03826b817cb2";
      };
    };
    "utils-merge-1.0.0" = {
      name = "utils-merge";
      packageName = "utils-merge";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/utils-merge/-/utils-merge-1.0.0.tgz";
        sha1 = "0294fb922bb9375153541c4f7096231f287c8af8";
      };
    };
    "vary-1.1.0" = {
      name = "vary";
      packageName = "vary";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vary/-/vary-1.1.0.tgz";
        sha1 = "e1e5affbbd16ae768dd2674394b9ad3022653140";
      };
    };
    "mime-types-2.1.13" = {
      name = "mime-types";
      packageName = "mime-types";
      version = "2.1.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-types/-/mime-types-2.1.13.tgz";
        sha1 = "e07aaa9c6c6b9a7ca3012c69003ad25a39e92a88";
      };
    };
    "negotiator-0.6.1" = {
      name = "negotiator";
      packageName = "negotiator";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/negotiator/-/negotiator-0.6.1.tgz";
        sha1 = "2b327184e8992101177b28563fb5e7102acd0ca9";
      };
    };
    "mime-db-1.25.0" = {
      name = "mime-db";
      packageName = "mime-db";
      version = "1.25.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-db/-/mime-db-1.25.0.tgz";
        sha1 = "c18dbd7c73a5dbf6f44a024dc0d165a1e7b1c392";
      };
    };
    "ms-0.7.1" = {
      name = "ms";
      packageName = "ms";
      version = "0.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-0.7.1.tgz";
        sha1 = "9cd13c03adbff25b65effde7ce864ee952017098";
      };
    };
    "statuses-1.3.1" = {
      name = "statuses";
      packageName = "statuses";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/statuses/-/statuses-1.3.1.tgz";
        sha1 = "faf51b9eb74aaef3b3acf4ad5f61abf24cb7b93e";
      };
    };
    "unpipe-1.0.0" = {
      name = "unpipe";
      packageName = "unpipe";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/unpipe/-/unpipe-1.0.0.tgz";
        sha1 = "b2bf4ee8514aae6165b4817829d21b2ef49904ec";
      };
    };
    "ee-first-1.1.1" = {
      name = "ee-first";
      packageName = "ee-first";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ee-first/-/ee-first-1.1.1.tgz";
        sha1 = "590c61156b0ae2f4f0255732a158b266bc56b21d";
      };
    };
    "forwarded-0.1.0" = {
      name = "forwarded";
      packageName = "forwarded";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/forwarded/-/forwarded-0.1.0.tgz";
        sha1 = "19ef9874c4ae1c297bcf078fde63a09b66a84363";
      };
    };
    "ipaddr.js-1.1.1" = {
      name = "ipaddr.js";
      packageName = "ipaddr.js";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ipaddr.js/-/ipaddr.js-1.1.1.tgz";
        sha1 = "c791d95f52b29c1247d5df80ada39b8a73647230";
      };
    };
    "destroy-1.0.4" = {
      name = "destroy";
      packageName = "destroy";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/destroy/-/destroy-1.0.4.tgz";
        sha1 = "978857442c44749e4206613e37946205826abd80";
      };
    };
    "http-errors-1.5.1" = {
      name = "http-errors";
      packageName = "http-errors";
      version = "1.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-errors/-/http-errors-1.5.1.tgz";
        sha1 = "788c0d2c1de2c81b9e6e8c01843b6b97eb920750";
      };
    };
    "mime-1.3.4" = {
      name = "mime";
      packageName = "mime";
      version = "1.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime/-/mime-1.3.4.tgz";
        sha1 = "115f9e3b6b3daf2959983cb38f149a2d40eb5d53";
      };
    };
    "inherits-2.0.3" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.3.tgz";
        sha1 = "633c2c83e3da42a502f52466022480f4208261de";
      };
    };
    "setprototypeof-1.0.2" = {
      name = "setprototypeof";
      packageName = "setprototypeof";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/setprototypeof/-/setprototypeof-1.0.2.tgz";
        sha1 = "81a552141ec104b88e89ce383103ad5c66564d08";
      };
    };
    "media-typer-0.3.0" = {
      name = "media-typer";
      packageName = "media-typer";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/media-typer/-/media-typer-0.3.0.tgz";
        sha1 = "8710d7af0aa626f8fffa1ce00168545263255748";
      };
    };
  };
  args = {
    name = "survey";
    packageName = "survey";
    version = "0.0.0";
    src = ./.;
    dependencies = [
      (sources."express-4.14.0" // {
        dependencies = [
          (sources."accepts-1.3.3" // {
            dependencies = [
              (sources."mime-types-2.1.13" // {
                dependencies = [
                  sources."mime-db-1.25.0"
                ];
              })
              sources."negotiator-0.6.1"
            ];
          })
          sources."array-flatten-1.1.1"
          sources."content-disposition-0.5.1"
          sources."content-type-1.0.2"
          sources."cookie-0.3.1"
          sources."cookie-signature-1.0.6"
          (sources."debug-2.2.0" // {
            dependencies = [
              sources."ms-0.7.1"
            ];
          })
          sources."depd-1.1.0"
          sources."encodeurl-1.0.1"
          sources."escape-html-1.0.3"
          sources."etag-1.7.0"
          (sources."finalhandler-0.5.0" // {
            dependencies = [
              sources."statuses-1.3.1"
              sources."unpipe-1.0.0"
            ];
          })
          sources."fresh-0.3.0"
          sources."merge-descriptors-1.0.1"
          sources."methods-1.1.2"
          (sources."on-finished-2.3.0" // {
            dependencies = [
              sources."ee-first-1.1.1"
            ];
          })
          sources."parseurl-1.3.1"
          sources."path-to-regexp-0.1.7"
          (sources."proxy-addr-1.1.2" // {
            dependencies = [
              sources."forwarded-0.1.0"
              sources."ipaddr.js-1.1.1"
            ];
          })
          sources."qs-6.2.0"
          sources."range-parser-1.2.0"
          (sources."send-0.14.1" // {
            dependencies = [
              sources."destroy-1.0.4"
              (sources."http-errors-1.5.1" // {
                dependencies = [
                  sources."inherits-2.0.3"
                  sources."setprototypeof-1.0.2"
                ];
              })
              sources."mime-1.3.4"
              sources."ms-0.7.1"
              sources."statuses-1.3.1"
            ];
          })
          sources."serve-static-1.11.1"
          (sources."type-is-1.6.14" // {
            dependencies = [
              sources."media-typer-0.3.0"
              (sources."mime-types-2.1.13" // {
                dependencies = [
                  sources."mime-db-1.25.0"
                ];
              })
            ];
          })
          sources."utils-merge-1.0.0"
          sources."vary-1.1.0"
        ];
      })
    ];
    buildInputs = globalBuildInputs;
    meta = {
    };
    production = true;
  };
in
{
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}